/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Social = {
  _id: string;
  _type: "social";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  icon?: string;
  color?: string;
  show?: boolean;
};

export type Quote = {
  _id: string;
  _type: "quote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text?: string;
  show?: boolean;
};

export type SkillReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "skill";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  slug?: Slug;
  summary?: string;
  description?: RichText;
  images?: Array<{
    _key: string;
  } & Figure>;
  links?: Array<{
    url?: string;
    icon?: string;
    label?: string;
    _type: "link";
    _key: string;
  }>;
  skills?: Array<{
    _key: string;
  } & SkillReference>;
  tags?: Array<string>;
  year?: number;
  featured?: boolean;
  show?: boolean;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  icon?: string;
  svg?: string;
  color?: string;
  inConstellation?: boolean;
  inSkillsList?: boolean;
  show?: boolean;
};

export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  color?: string;
  skills?: Array<{
    _key: string;
  } & SkillReference>;
  show?: boolean;
};

export type Language = {
  _id: string;
  _type: "language";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  flag?: string;
  proficiency?: "Native" | "Full professional" | "Professional working" | "Limited working" | "Elementary";
  reading?: number;
  speaking?: number;
  writing?: number;
  listening?: number;
  show?: boolean;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  institution?: string;
  start?: number;
  end?: number;
  logo?: Figure;
  link?: string;
  color?: string;
  icon?: string;
  show?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Figure = {
  _type: "figure";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  company?: string;
  type?: "Full-time" | "Part-time" | "Internship" | "Freelance" | "Contract";
  career?: boolean;
  start?: string;
  end?: string;
  logo?: Figure;
  link?: string;
  color?: string;
  description?: string;
  tasks?: Array<{
    title?: string;
    lines?: RichText;
    skills?: Array<{
      _key: string;
    } & SkillReference>;
    _type: "task";
    _key: string;
  }>;
  show?: boolean;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  emoji?: string;
  text?: RichText;
  image?: Figure;
  caption?: string;
  button?: {
    text?: string;
    link?: string;
  };
  show?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  site?: {
    title?: string;
    description?: string;
  };
  home?: {
    description?: string;
    heroEyebrow?: string;
    heroTitle?: string;
    heroLead?: string;
    aboutGreeting?: string;
  };
  resume?: {
    description?: string;
    eyebrow?: string;
    title?: string;
    summary?: RichText;
    phone?: string;
    email?: string;
    cv?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  projects?: {
    description?: string;
    lead?: string;
  };
  footer?: {
    friends?: Array<{
      name?: string;
      url?: string;
      image?: Figure;
      color?: string;
      _type: "friend";
      _key: string;
    }>;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Social | Quote | SkillReference | Project | RichText | Slug | Skill | SkillCategory | Language | Education | SanityImageAssetReference | Figure | Experience | About | SanityFileAssetReference | SiteSettings | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../website/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    site{ title, description },    home{ description, heroEyebrow, heroTitle, heroLead, aboutGreeting },    resume{ description, eyebrow, title, summary, phone, email, "cv": cv.asset->url },    projects{ description, lead },    footer{ friends[]{ _key, name, url, color, "image": image{ asset, alt, hotspot, crop } } }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  site: {
    title: string | null;
    description: string | null;
  } | null;
  home: {
    description: string | null;
    heroEyebrow: string | null;
    heroTitle: string | null;
    heroLead: string | null;
    aboutGreeting: string | null;
  } | null;
  resume: {
    description: string | null;
    eyebrow: string | null;
    title: string | null;
    summary: RichText | null;
    phone: string | null;
    email: string | null;
    cv: string | null;
  } | null;
  projects: {
    description: string | null;
    lead: string | null;
  } | null;
  footer: {
    friends: Array<{
      _key: string;
      name: string | null;
      url: string | null;
      color: string | null;
      image: {
        asset: SanityImageAssetReference | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
    }> | null;
  } | null;
} | null;

// Source: ../website/sanity/queries.ts
// Variable: ABOUTS_QUERY
// Query: *[_type == "about" && show != false] | order(orderRank asc){    _id,    title,    emoji,    "image": image{ asset, alt, hotspot, crop },    caption,    text,    button{ text, link }  }
export type ABOUTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  emoji: string | null;
  image: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  caption: string | null;
  text: RichText | null;
  button: {
    text: string | null;
    link: string | null;
  } | null;
}>;

// Source: ../website/sanity/queries.ts
// Variable: SKILL_CATEGORIES_QUERY
// Query: *[_type == "skillCategory" && show != false] | order(orderRank asc){    _id,    title,    color,    "skills": skills[@->show != false]->{ _id, name, icon, svg, color, inConstellation, inSkillsList }  }
export type SKILL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  color: string | null;
  skills: Array<{
    _id: string;
    name: string | null;
    icon: string | null;
    svg: string | null;
    color: string | null;
    inConstellation: boolean | null;
    inSkillsList: boolean | null;
  }> | null;
}>;

// Source: ../website/sanity/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience" && show != false] | order(start asc){    _id,    title,    company,    type,    career,    start,    end,    "logo": logo{ asset, alt, hotspot, crop },    link,    color,    description,    tasks[]{      _key,      title,      lines,      "skills": skills[@->show != false]->{ _id, name }    }  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  company: string | null;
  type: "Contract" | "Freelance" | "Full-time" | "Internship" | "Part-time" | null;
  career: boolean | null;
  start: string | null;
  end: string | null;
  logo: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  link: string | null;
  color: string | null;
  description: string | null;
  tasks: Array<{
    _key: string;
    title: string | null;
    lines: RichText | null;
    skills: Array<{
      _id: string;
      name: string | null;
    }> | null;
  }> | null;
}>;

// Source: ../website/sanity/queries.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "education" && show != false] | order(start asc){    _id,    title,    institution,    start,    end,    "logo": logo{ asset, alt, hotspot, crop },    link,    color,    icon  }
export type EDUCATION_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  institution: string | null;
  start: number | null;
  end: number | null;
  logo: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  link: string | null;
  color: string | null;
  icon: string | null;
}>;

// Source: ../website/sanity/queries.ts
// Variable: LANGUAGES_QUERY
// Query: *[_type == "language" && show != false] | order(orderRank asc){    _id,    name,    flag,    reading,    speaking,    writing,    listening,    proficiency  }
export type LANGUAGES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  flag: string | null;
  reading: number | null;
  speaking: number | null;
  writing: number | null;
  listening: number | null;
  proficiency: "Elementary" | "Full professional" | "Limited working" | "Native" | "Professional working" | null;
}>;

// Source: ../website/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && show != false] | order(year desc, orderRank asc){    _id,    name,    slug,    summary,    description,    "images": images[]{ _key, asset, alt, hotspot, crop },    links[]{ _key, icon, url, label },    "skills": skills[@->show != false]->{ _id, name },    tags,    year,    featured  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  summary: string | null;
  description: RichText | null;
  images: Array<{
    _key: string;
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  links: Array<{
    _key: string;
    icon: string | null;
    url: string | null;
    label: string | null;
  }> | null;
  skills: Array<{
    _id: string;
    name: string | null;
  }> | null;
  tags: Array<string> | null;
  year: number | null;
  featured: boolean | null;
}>;

// Source: ../website/sanity/queries.ts
// Variable: QUOTES_QUERY
// Query: *[_type == "quote" && show != false]{ _id, text }
export type QUOTES_QUERY_RESULT = Array<{
  _id: string;
  text: string | null;
}>;

// Source: ../website/sanity/queries.ts
// Variable: SOCIALS_QUERY
// Query: *[_type == "social" && show != false] | order(orderRank asc){    _id,    name,    icon,    color,    url  }
export type SOCIALS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  icon: string | null;
  color: string | null;
  url: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    "\n  *[_type == \"siteSettings\"][0]{\n    site{ title, description },\n    home{ description, heroEyebrow, heroTitle, heroLead, aboutGreeting },\n    resume{ description, eyebrow, title, summary, phone, email, \"cv\": cv.asset->url },\n    projects{ description, lead },\n    footer{ friends[]{ _key, name, url, color, \"image\": image{ asset, alt, hotspot, crop } } }\n  }\n": SITE_SETTINGS_QUERY_RESULT;
    "\n  *[_type == \"about\" && show != false] | order(orderRank asc){\n    _id,\n    title,\n    emoji,\n    \"image\": image{ asset, alt, hotspot, crop },\n    caption,\n    text,\n    button{ text, link }\n  }\n": ABOUTS_QUERY_RESULT;
    "\n  *[_type == \"skillCategory\" && show != false] | order(orderRank asc){\n    _id,\n    title,\n    color,\n    \"skills\": skills[@->show != false]->{ _id, name, icon, svg, color, inConstellation, inSkillsList }\n  }\n": SKILL_CATEGORIES_QUERY_RESULT;
    "\n  *[_type == \"experience\" && show != false] | order(start asc){\n    _id,\n    title,\n    company,\n    type,\n    career,\n    start,\n    end,\n    \"logo\": logo{ asset, alt, hotspot, crop },\n    link,\n    color,\n    description,\n    tasks[]{\n      _key,\n      title,\n      lines,\n      \"skills\": skills[@->show != false]->{ _id, name }\n    }\n  }\n": EXPERIENCE_QUERY_RESULT;
    "\n  *[_type == \"education\" && show != false] | order(start asc){\n    _id,\n    title,\n    institution,\n    start,\n    end,\n    \"logo\": logo{ asset, alt, hotspot, crop },\n    link,\n    color,\n    icon\n  }\n": EDUCATION_QUERY_RESULT;
    "\n  *[_type == \"language\" && show != false] | order(orderRank asc){\n    _id,\n    name,\n    flag,\n    reading,\n    speaking,\n    writing,\n    listening,\n    proficiency\n  }\n": LANGUAGES_QUERY_RESULT;
    "\n  *[_type == \"project\" && show != false] | order(year desc, orderRank asc){\n    _id,\n    name,\n    slug,\n    summary,\n    description,\n    \"images\": images[]{ _key, asset, alt, hotspot, crop },\n    links[]{ _key, icon, url, label },\n    \"skills\": skills[@->show != false]->{ _id, name },\n    tags,\n    year,\n    featured\n  }\n": PROJECTS_QUERY_RESULT;
    "\n  *[_type == \"quote\" && show != false]{ _id, text }\n": QUOTES_QUERY_RESULT;
    "\n  *[_type == \"social\" && show != false] | order(orderRank asc){\n    _id,\n    name,\n    icon,\n    color,\n    url\n  }\n": SOCIALS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}

